version: "3"

services:
  namenode:
    image: digitbrain/bb-hdfs:namenode-hadoop3.3.0-java11
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: digitbrain/bb-hdfs:datanode-hadoop3.3.0-java11
    container_name: datanode
    restart: always
    volumes:
      - ./hadoop/datanode/1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode2:
    image: digitbrain/bb-hdfs:datanode-hadoop3.3.0-java11
    container_name: datanode2
    restart: always
    volumes:
      - ./hadoop/datanode/2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode3:
    image: digitbrain/bb-hdfs:datanode-hadoop3.3.0-java11
    container_name: datanode3
    restart: always
    volumes:
      - ./hadoop/datanode/3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
